# Generated by Django 5.2.1 on 2025-06-01 13:19

import fashion_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', fashion_app.models.UserManager()),
            ],
        ),
    ]
