# Generated by Django 5.2.1 on 2025-06-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
